version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=apple123
    volumes:
      - ./db/:/var/lib/postgresql/data
      
  redis:
    image: redis:6
    restart: always

  auth:
    build: auth
    restart: always
    environment:
      - DB_DSN=user=postgres host=db password=apple123 dbname=postgres port=5432 sslmode=disable
      # - ELS_BASE=http://elastic:9200/
      - IMG_SER=http://uploader:8083/
      - NOTIF_SER=http://notification:8084/
      - REDIS=redis:6379
    depends_on:
      - db
  gateway:
    build: gateway
    restart: always
    depends_on:
      - auth
    ports:
      - 8000:3000
    volumes:
      - ./img/:/root/app/img
  web:
    build: web
    restart: always
    environment:
      - DB_DSN=user=postgres host=db password=apple123 dbname=postgres port=5432 sslmode=disable
      - ELS_BASE=http://elastic:9200/
      - IMG_SER=http://uploader:8083/
      - NOTIF_SER=http://notification:8084/
    depends_on:
      - auth
  uploader:
    build: uploader
    restart: always
    environment:
      - DB_DSN=user=postgres host=db password=apple123 dbname=postgres port=5432 sslmode=disable
    volumes:
      - ./img/:/root/app/img
    depends_on:
      - auth
  notification:
    build: notification
    restart: always
    environment:
      - DB_DSN=user=postgres host=db password=apple123 dbname=postgres port=5432 sslmode=disable
      - AUTH_SER=http://auth:8080/
    depends_on:
      - auth
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ports:
      # - 9200:9200
      # - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./els_data/:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1