### Hello World
GET http://localhost:8080/
Accept: application/json

### Get Picture Lists
GET http://localhost:8080/pictures/
Accept: application/json

### Post Picture
POST http://localhost:8080/pictures/
Accept: application/json

{
	"title": "helloworld",
    "uid": 3
}

### Reigster
POST http://localhost:8080/users/
Accept: application/json

{
	"username": "ttt4",
    "password": "apple123",
    "nickname": "apple"
}

### Login
POST http://localhost:8080/users/login/
Accept: application/json

{
	"username": "ttt4",
    "password": "apple123"
}


### Check info
GET http://localhost:8080/users/
Accept: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MX0.3JUcVbjI8u8rA9zG1L0fvlSuQyuJ-Ch0YkFFYsZ0fR8GLmcVZwRmIjJcoG530gXxWsdfCYYMYKIqPwH8XeIVqg
