@baseUrl =http://whiteboard.house:8000/user/
# @baseUrl =http://localhost:8000/user/
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDM3MjU5MjZ9.mcmUxB4BBi52OID6z1bwy-cGwyMbXVHo7htIisSitQCstSytjBVGeRkRLUFr59uc0Zk13X794w5IqFMyHrzTSA
@refresh = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjpmYWxzZSwiRXhwaXJlIjoxNjE5Mjc2NzI2fQ.Bx24G-qzCAmemhL2sfolpprXqBHMMtdE6x-Ik11d5Jtvbrf6H9mbnxohZIGNZrZaLhjq2RC9ClYwCE11FV0o6A
### Get user detail 
GET {{baseUrl}}1
Accept: application/json

### Reigster
POST {{baseUrl}}
Accept: application/json

{
	"username": "ttt1",
    "password": "apple123",
    "nickname": "apple"
}


### Login
POST {{baseUrl}}login/
Accept: application/json

{
	"username": "ttt1",
    "password": "apple123"
}

### Check info
GET {{baseUrl}}
Accept: application/json
Authorization: {{token}}


### Update detail
PUT {{baseUrl}}
Accept: application/json
Authorization: {{token}}

{
	"Nickname": "Tecty",
    "Signature": "I am a good photographer, contact me with wechat: myTecty",
    "Img": 1
}

### Refresh Token 
POST {{baseUrl}}refresh/
Accept: application/json

{
    "Refresh": "{{refresh}}"
}

