@baseUrl =http://localhost:3000/user/
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDMxOTA2OTd9.wltQlGOnpd7vkWO0zjOIEKAchUECw27NxmFiZHXQKDPcduE_qRC85cmT41dM_YhZbBd24RET1oQCQcpuIwtErA
@refresh = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjpmYWxzZSwiRXhwaXJlIjoxNjE4NzQxNDk3fQ.L9iaz76QRFyEpl3vf_Jp8_fq1hoz3tDhGPT6UhX3Y3faBIQRZIkM-WjH0o9GcA_V2D1r1hqkXXFTZcA0fgn2Gw
### Get user detail 
GET {{baseUrl}}1
Accept: application/json

### Reigster
POST {{baseUrl}}
Accept: application/json

{
	"username": "ttt1",
    "password": "apple123",
    "nickname": "apple"
}


### Login
POST {{baseUrl}}login/
Accept: application/json

{
	"username": "ttt1",
    "password": "apple123"
}

### Check info
GET {{baseUrl}}
Accept: application/json
Authorization: {{token}}


### Update detail
PUT {{baseUrl}}
Accept: application/json
Authorization: {{token}}

{
	"Nickname": "Tecty",
    "Signature": "I am a good photographer, contact me with wechat: myTecty",
    "Img": 1
}

### Refresh Token 
POST {{baseUrl}}refresh/
Accept: application/json

{
    "Refresh": "{{refresh}}"
}

