# @baseUrl=http://localhost:8000/els/
@baseUrl=http://whiteboard.house:8000/els/

### Get particular doc
GET  {{baseUrl}}picture/_doc/3
Content-Type: application/json

### Get all and pagination
POST {{baseUrl}}picture/_search
Content-Type: application/json

{
  "from": 0,
  "size": 10,
  "sort" : [
    { "NView" : "desc" },
    { "NLike" : "desc" }
  ]
}

### Get Picture By User
POST {{baseUrl}}picture/_search
Content-Type: application/json

{
  "from": 0,
  "size": 1,
  "query":{
      "match": {
          "UserID": 1
      }
  }
}

### Get Picture By User
POST {{baseUrl}}picture/_search
Content-Type: application/json

{
  "from": 0,
  "size": 1,
  "query":{
      "match": {
          "UserID": 16
      }
  }
}

### Search
POST {{baseUrl}}picture/_search
Content-Type: application/json

{
  "from": 0,
  "size": 10,
  "query":{
    "multi_match":{
      "query":"hello",
      "fields":[
        "Title", "Tags.Name"
      ]
    }
  }
}

### Search
GET {{baseUrl}}picture/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": {
        "multi_match":{
          "query":"helloworld",
          "fields":[
            "Title", "Tags.Name"
          ]
        }
      },
      "filter": {
        "geo_bounding_box": {
          "GeoHash": {
            "top_left": {
              "lat": 4,
              "lon": 1
            },
            "bottom_right": {
              "lat": 3,
              "lon": 2
            }
          }
        }
      }
    }
  }
}

### Geo base search
POST {{baseUrl}}picture/_search
Content-Type: application/json

{
  "from": 0,
  "size": 10,
  "query": {
    "geo_bounding_box": {
      "GeoHash": {
        "top_left": {
          "lat": 4,
          "lon": 1
        },
        "bottom_right": {
          "lat": 3,
          "lon": 2
        }
      }
    }
  }
}

### Get Comment 
GET  {{baseUrl}}comment/_search
Content-Type: application/json

{
  "from": 0,
  "size": 10,
  "query":{
      "match": {
          "PictureID": 106
      }
  }
}

