@baseUrl=http://localhost:8084/
# @baseUrl=http://localhost:8000/message/
# @baseUrl=http://whiteboard.house:8000/message/
@auth=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDUzMjkzMzN9.HFKPKGlg2fdJSe5OJxfQE8Ny03BITX1E2qqgxgpJ95FiO16vfu4e9oJ7EA0ufWj7AI6WoR91EmEJC8oxNgfT3w
### Get all this user's notifications
GET {{baseUrl}}
Accept: application/json
Authorization: {{auth}}

### Post a new notifications 
POST {{baseUrl}}
Accept: application/json

{
    "UID":1,
    "Actor": 1,
	"Type": "follow"
}

### removing all the notification of a user  
DELETE {{baseUrl}}
Accept: application/json
Authorization: {{auth}}
