# @baseUrl=http://localhost:8081/
@baseUrl=http://whiteboard.house:8000/picture/
# @baseUrl=http://localhost:8000/picture/

### Hello World
GET {{baseUrl}}
Accept: application/json

### Get Picture Lists
GET {{baseUrl}}1
Accept: application/json

### Get Picture Detail
POST {{baseUrl}}picture/1
Accept: application/json

### Post Picture
POST {{baseUrl}}
Accept: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDM4MDcxMjJ9.k0vuSUqEADxjUrlJye7RLaQxUwagCx4Mxem7XJgLZQLuUg9aGrMzTAJZ6X5Lk-qVBF2wXy7isRl2wIlD0RZ1ZQ

{
	"title": "helloworld",
    "Img": 1,
    "lat": 3.44,
    "lng": 1.22,
    "location" : {
        "country":"Australia",
        "state":"NSW",
        "city":"Sydney"
    },
    "Iso":400,
    "FocalLength":2,
    "Aperture":2.5,
    "ShutterSpeed":0.24,
    "Timestamp":2147483647,
    "Orientation": 24,
    "Elevation": 123.43,
    "Tags": ["hello", "world"]
}


