@baseUrl=http://localhost:8081/
# @baseUrl=http://localhost:8000/picture/
# @baseUrl=http://whiteboard.house:8000/picture/
@auth=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MiwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDUyNTMwMDF9.smt7an9cRX53e4ihhX2EjDolk9nv9zXmWqFSTBUUMi5iN5HPJzP4jeU0x2CxUyGVktv82iT_feQuSu4W_JoimA

### Get Picture Lists
GET {{baseUrl}}
Accept: application/json

### Get Picture Detail
GET {{baseUrl}}3
Accept: application/json

### Post Picture
POST {{baseUrl}}
Accept: application/json
Authorization: {{auth}}

{
	"title": "helloworld",
	"body":"This is a hello world post",
    "Img": 1,
    "lat": 3.44,
    "lng": 1.22,
    "location" : {
        "country":"Australia",
        "state":"NSW",
        "city":"Sydney"
    },
    "Iso":400,
    "FocalLength":2,
    "Aperture":2.5,
    "ShutterSpeed":0.24,
    "Timestamp":2147483647,
    "Orientation": 24,
    "Elevation": 123.43,
    "Weather":"cloudy",
    "Tags": ["cloudy", "forest"]
}

### Delete a Picture
DELETE {{baseUrl}}9
Authorization: {{auth}}

### Comment 
POST {{baseUrl}}3/comment
Accept: application/json
Authorization: {{auth}}

{
    "message":"I really like this photo!"
}

### Delete Commnet, This id is not the picture id, is comment id 
DELETE  {{baseUrl}}1/comment
Accept: application/json
Authorization: {{auth}}

### 
# Like and dislike always success unless the backend loss db connection or some edge cases 
# One person only can choose one attitute - Like or dislike
# Thus, the like count is unique by uid, pictureid and attitute. 
# The count will be update to elastic search asynchronously
### Like 
POST {{baseUrl}}3/like
Accept: application/json
Authorization: {{auth}}


### Dislike
POST {{baseUrl}}3/dislike
Accept: application/json
Authorization: {{auth}}

### 
# remove like or dislike are same functions in backend
# thus, they have same side effects
### remove dislike 
DELETE  {{baseUrl}}3/dislike
Accept: application/json
Authorization: {{auth}}

### remove like 
DELETE  {{baseUrl}}3/dislike
Accept: application/json
Authorization: {{auth}}
