@baseUrl=http://localhost:8081/
# @baseUrl=http://localhost:8000/picture/
# @baseUrl=http://whiteboard.house:8000/picture/
@auth=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiQWNjZXNzIjp0cnVlLCJFeHBpcmUiOjE2MDQwNDQ4MTV9.pr-mH_7xqqjuQ5krOCsugsEyVDq48TRRoiAuZC2KMKu1Nb1JHmer4G1cMF5ZvwMuFYeSJY_HuDYzTZsUOx6p8g

### Hello World
GET {{baseUrl}}
Accept: application/json

### Get Picture Lists
GET {{baseUrl}}
Accept: application/json

### Get Picture Detail
GET {{baseUrl}}1
Accept: application/json

### Post Picture
POST {{baseUrl}}
Accept: application/json
Authorization: {{auth}}

{
	"title": "helloworld",
    "Img": 7,
    "lat": 3.44,
    "lng": 1.22,
    "location" : {
        "country":"Australia",
        "state":"NSW",
        "city":"Sydney"
    },
    "Iso":400,
    "FocalLength":2,
    "Aperture":2.5,
    "ShutterSpeed":0.24,
    "Timestamp":2147483647,
    "Orientation": 24,
    "Elevation": 123.43,
    "Tags": ["cloudy", "forest"]
}



### Comment 
POST {{baseUrl}}6/comment
Accept: application/json
Authorization: {{auth}}

{
    "message":"I really like this photo!"
}

### 
# Like and dislike always success unless the backend loss db connection or some edge cases 
# One person only can choose one attitute - Like or dislike
# Thus, the like count is unique by uid, pictureid and attitute. 
# The count will be update to elastic search asynchronously
### Like 
POST {{baseUrl}}1/like
Accept: application/json
Authorization: {{auth}}


### Dislike
POST {{baseUrl}}1/dislike
Accept: application/json
Authorization: {{auth}}
